let g:syntastic_java_javac_classpath="./src\n"
let g:syntastic_java_javac_classpath.="./libs/commons-cli-1.2/commons-cli-1.2.jar\n"
let g:syntastic_java_javac_classpath.="./libs/weka.jar\n"
let g:syntastic_java_javac_classpath.="./libs/LibLINEAR.jar\n"
let g:syntastic_java_javac_classpath.="./libs/WekaLibSVM.jar"
